name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - "**/README.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            krast/docker-transmission:latest
            ghcr.io/Krast76/docker-transmission:latest

      -
        if: contains(github.ref, 'refs/tags/v')
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            krast/docker-transmission:${GITHUB_REF}
            ghcr.io/Krast76/docker-transmission:${GITHUB_REF}
